# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170319_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
